meta_product_name: "Rémi Tondeux - Portfolio"
meta_title: "Discover me & let's work together !"
meta_description: "Welcome to my portfolio. Here you will learn a bit more about who I am and skills I have. Contact me and maybe start working together !"
meta_image: "banner.jpeg" # should exist in `app/assets/images/`
